### ISSUE TITLE
Issue at line 7

### ISSUE THREAD

**Issue by rahulakolkar** [udacity/nd064_course_1#29]
Error while build dockerfile-
 > [4/4] RUN go build  -o helloworld:
#9 3.219 go: go.mod file not found in current directory or any parent directory; see 'go help modules'
------
executor failed running [/bin/sh -c go build  -o helloworld]: exit code: 1

Add **RUN go mod init** before line 7 to resolve issue

https://github.com/udacity/nd064_course_1/blob/7e67594c98e81c96ae2ac092101957d17277815f/solutions/go-helloworld/Dockerfile#L7

**Comment by kgamanji** [comment]
Fixed in PR https://github.com/udacity/nd064_course_1/pull/75
