### ISSUE TITLE
YAML syntax error

### ISSUE THREAD

**Issue by aungzanbaw** [udacity/nd064_course_1#36]
There is a string concat problem, first pointed out by my VS Code editor. I tried followings, but don't work either way
YAML  `key: value with some example:: something else `
Output `key: value with some example: something else` 

YAML  `key: value with some example":" something else `

It's on [deployment.yaml](https://github.com/udacity/nd064_course_1/blob/main/solutions/helm/python-helloworld/templates/deployment.yaml)

**Comment by kgamanji** [comment]
The file is parsed correctly as YAML. Seems like a VSCode issue: https://github.com/redhat-developer/vscode-yaml/issues/290

Not a priority to fix, hence closing the issue.
