### ISSUE TITLE
Go Hello World Video Instruction Update

### ISSUE THREAD

**Issue by ericcgu** [udacity/nd064_course_1#57]
@kgamanji 

Error: failed to create containerd container: get apparmor_parser version: exec: "apparmor_parser": executable file not found

Should add `zypper update && zypper install apparmor-parser` to Vagrant startup bootstrap script so students can follow.

**Comment by kgamanji** [comment]
Fixed in PR https://github.com/udacity/nd064_course_1/pull/75
