### ISSUE TITLE
"itsdangerous" version incompatibility in techtrends

### ISSUE THREAD

**Issue by sgeorgie** [udacity/nd064_course_1#77]
Installing the python dependencies using pip3 and running the project as is throws the following exception:

```
» python app.py 

Traceback (most recent call last):
  File "app.py", line 3, in <module>
    from flask import Flask, jsonify, json, render_template, request, url_for, redirect, flash
  File "/usr/local/lib/python3.8/site-packages/flask/__init__.py", line 19, in <module>
    from . import json
  File "/usr/local/lib/python3.8/site-packages/flask/json/__init__.py", line 15, in <module>
    from itsdangerous import json as _json
ImportError: cannot import name 'json' from 'itsdangerous' (/usr/local/lib/python3.8/site-packages/itsdangerous/__init__.py)
```

I'm running python 3.8.12 on MacOS 11.5.2

It seems that a lot of people started getting this error this morning in their projects due to a breaking "itsdangerous" library update.

**Comment by sgeorgie** [comment]
I was able to fix it by explicitly setting the version of "itsdangerous" in `requirements.txt` as such: `itsdangerous==2.0.1`

**Comment by SudKul** [comment]
Hey @sgeorgie 
It is a good practice to use the "specific" packages. 

Besides, should you (or any learner) need help on individual issues, we recommend using the https://knowledge.udacity.com/ platform to discuss with our experienced mentors.
